### ISSUE TITLE
Error returned: Exception: not a Crofile

### ISSUE THREAD

**Issue by davidszakonyi** [alephdata/cronodump#12]
Very neat package, but I'm having trouble dumping about 20 Cronos databases. Here's the error:

(base) computer cronodump-master % bin/croconvert --csv "Banks/Cronosd/“

unknown magic:  b'Cr\xeeFile\x00'
Traceback (most recent call last):
  File "/Users/computer/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/computer/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/computer/Documents/cronodump-master/crodump/croconvert.py", line 139, in <module>
    main()
  File "/Users/computer/Documents/cronodump-master/crodump/croconvert.py", line 133, in main
    csv_output(kod, args)
  File "/Users/computer/Documents/cronodump-master/crodump/croconvert.py", line 41, in csv_output
    db = Database(args.dbdir, kod)
  File "/Users/computer/Documents/cronodump-master/crodump/Database.py", line 32, in __init__
    self.stru = self.getfile("Stru")
  File "/Users/computer/Documents/cronodump-master/crodump/Database.py", line 55, in getfile
    return Datafile(name, open(datname, "rb"), open(tadname, "rb"), self.kod)
  File "/Users/computer/Documents/cronodump-master/crodump/Datafile.py", line 16, in __init__
    self.readdathdr()
  File "/Users/computer/Documents/cronodump-master/crodump/Datafile.py", line 63, in readdathdr
    raise Exception("not a Crofile")
Exception: not a Crofile

And here's the file listing. Happy to share the database if that would help.

CroBank.dat
CroBank.tad
CroIndex.dat
CroIndex.tad
CroStru.dat
CroStru.tad

**Comment by nlitsme** [comment]
hmm,  `\xee`  happens to be the cyrillic 'о'  which looks a lot like the latin 'o'

Can you send me a link where I can download that db?

**Comment by davidszakonyi** [comment]
You were exactly right - the hex was broken. I figured it out and got it to
work. Thanks for
